name: Cypress Tests
on: 
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ] 

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # Runs tests in parallel with matrix strategy https://docs.cypress.io/guides/guides/parallelization
    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    # Also see warning here https://github.com/cypress-io/github-action#parallel
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [1] 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: npm install -D cypress-xpath
      
      - name: cypress run
        uses: cypress-io/github-action@v6
        with: 
            start: npm start
            record: true
            browser: chrome
        env:
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run cypress-clound